#!/bin/bash

if [ $# -ne 1 ]; then
	echo "Error: Invalid number of arguments"
	exit 1
fi 

input=$1
if ! [[ $input =~ ^[0-9]{4}$ ]]; then
	echo "Error: Input must be a 4-digit integer"
	exit 1
fi

echo -n $input | sha256sum | awk '{print $1}' >> hash_output.txt
